require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MailstartsController do

  # This should return the minimal set of attributes required to create a valid
  # Mailstart. As you add validations to Mailstart, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all mailstarts as @mailstarts" do
      mailstart = Mailstart.create! valid_attributes
      get :index
      assigns(:mailstarts).should eq([mailstart])
    end
  end

  describe "GET show" do
    it "assigns the requested mailstart as @mailstart" do
      mailstart = Mailstart.create! valid_attributes
      get :show, :id => mailstart.id.to_s
      assigns(:mailstart).should eq(mailstart)
    end
  end

  describe "GET new" do
    it "assigns a new mailstart as @mailstart" do
      get :new
      assigns(:mailstart).should be_a_new(Mailstart)
    end
  end

  describe "GET edit" do
    it "assigns the requested mailstart as @mailstart" do
      mailstart = Mailstart.create! valid_attributes
      get :edit, :id => mailstart.id.to_s
      assigns(:mailstart).should eq(mailstart)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mailstart" do
        expect {
          post :create, :mailstart => valid_attributes
        }.to change(Mailstart, :count).by(1)
      end

      it "assigns a newly created mailstart as @mailstart" do
        post :create, :mailstart => valid_attributes
        assigns(:mailstart).should be_a(Mailstart)
        assigns(:mailstart).should be_persisted
      end

      it "redirects to the created mailstart" do
        post :create, :mailstart => valid_attributes
        response.should redirect_to(Mailstart.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mailstart as @mailstart" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mailstart.any_instance.stub(:save).and_return(false)
        post :create, :mailstart => {}
        assigns(:mailstart).should be_a_new(Mailstart)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mailstart.any_instance.stub(:save).and_return(false)
        post :create, :mailstart => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mailstart" do
        mailstart = Mailstart.create! valid_attributes
        # Assuming there are no other mailstarts in the database, this
        # specifies that the Mailstart created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mailstart.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => mailstart.id, :mailstart => {'these' => 'params'}
      end

      it "assigns the requested mailstart as @mailstart" do
        mailstart = Mailstart.create! valid_attributes
        put :update, :id => mailstart.id, :mailstart => valid_attributes
        assigns(:mailstart).should eq(mailstart)
      end

      it "redirects to the mailstart" do
        mailstart = Mailstart.create! valid_attributes
        put :update, :id => mailstart.id, :mailstart => valid_attributes
        response.should redirect_to(mailstart)
      end
    end

    describe "with invalid params" do
      it "assigns the mailstart as @mailstart" do
        mailstart = Mailstart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mailstart.any_instance.stub(:save).and_return(false)
        put :update, :id => mailstart.id.to_s, :mailstart => {}
        assigns(:mailstart).should eq(mailstart)
      end

      it "re-renders the 'edit' template" do
        mailstart = Mailstart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mailstart.any_instance.stub(:save).and_return(false)
        put :update, :id => mailstart.id.to_s, :mailstart => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mailstart" do
      mailstart = Mailstart.create! valid_attributes
      expect {
        delete :destroy, :id => mailstart.id.to_s
      }.to change(Mailstart, :count).by(-1)
    end

    it "redirects to the mailstarts list" do
      mailstart = Mailstart.create! valid_attributes
      delete :destroy, :id => mailstart.id.to_s
      response.should redirect_to(mailstarts_url)
    end
  end

end
