require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NewslettertimingprogrammingsController do

  # This should return the minimal set of attributes required to create a valid
  # Newslettertimingprogramming. As you add validations to Newslettertimingprogramming, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all newslettertimingprogrammings as @newslettertimingprogrammings" do
      newslettertimingprogramming = Newslettertimingprogramming.create! valid_attributes
      get :index
      assigns(:newslettertimingprogrammings).should eq([newslettertimingprogramming])
    end
  end

  describe "GET show" do
    it "assigns the requested newslettertimingprogramming as @newslettertimingprogramming" do
      newslettertimingprogramming = Newslettertimingprogramming.create! valid_attributes
      get :show, :id => newslettertimingprogramming.id.to_s
      assigns(:newslettertimingprogramming).should eq(newslettertimingprogramming)
    end
  end

  describe "GET new" do
    it "assigns a new newslettertimingprogramming as @newslettertimingprogramming" do
      get :new
      assigns(:newslettertimingprogramming).should be_a_new(Newslettertimingprogramming)
    end
  end

  describe "GET edit" do
    it "assigns the requested newslettertimingprogramming as @newslettertimingprogramming" do
      newslettertimingprogramming = Newslettertimingprogramming.create! valid_attributes
      get :edit, :id => newslettertimingprogramming.id.to_s
      assigns(:newslettertimingprogramming).should eq(newslettertimingprogramming)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Newslettertimingprogramming" do
        expect {
          post :create, :newslettertimingprogramming => valid_attributes
        }.to change(Newslettertimingprogramming, :count).by(1)
      end

      it "assigns a newly created newslettertimingprogramming as @newslettertimingprogramming" do
        post :create, :newslettertimingprogramming => valid_attributes
        assigns(:newslettertimingprogramming).should be_a(Newslettertimingprogramming)
        assigns(:newslettertimingprogramming).should be_persisted
      end

      it "redirects to the created newslettertimingprogramming" do
        post :create, :newslettertimingprogramming => valid_attributes
        response.should redirect_to(Newslettertimingprogramming.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved newslettertimingprogramming as @newslettertimingprogramming" do
        # Trigger the behavior that occurs when invalid params are submitted
        Newslettertimingprogramming.any_instance.stub(:save).and_return(false)
        post :create, :newslettertimingprogramming => {}
        assigns(:newslettertimingprogramming).should be_a_new(Newslettertimingprogramming)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Newslettertimingprogramming.any_instance.stub(:save).and_return(false)
        post :create, :newslettertimingprogramming => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested newslettertimingprogramming" do
        newslettertimingprogramming = Newslettertimingprogramming.create! valid_attributes
        # Assuming there are no other newslettertimingprogrammings in the database, this
        # specifies that the Newslettertimingprogramming created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Newslettertimingprogramming.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => newslettertimingprogramming.id, :newslettertimingprogramming => {'these' => 'params'}
      end

      it "assigns the requested newslettertimingprogramming as @newslettertimingprogramming" do
        newslettertimingprogramming = Newslettertimingprogramming.create! valid_attributes
        put :update, :id => newslettertimingprogramming.id, :newslettertimingprogramming => valid_attributes
        assigns(:newslettertimingprogramming).should eq(newslettertimingprogramming)
      end

      it "redirects to the newslettertimingprogramming" do
        newslettertimingprogramming = Newslettertimingprogramming.create! valid_attributes
        put :update, :id => newslettertimingprogramming.id, :newslettertimingprogramming => valid_attributes
        response.should redirect_to(newslettertimingprogramming)
      end
    end

    describe "with invalid params" do
      it "assigns the newslettertimingprogramming as @newslettertimingprogramming" do
        newslettertimingprogramming = Newslettertimingprogramming.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Newslettertimingprogramming.any_instance.stub(:save).and_return(false)
        put :update, :id => newslettertimingprogramming.id.to_s, :newslettertimingprogramming => {}
        assigns(:newslettertimingprogramming).should eq(newslettertimingprogramming)
      end

      it "re-renders the 'edit' template" do
        newslettertimingprogramming = Newslettertimingprogramming.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Newslettertimingprogramming.any_instance.stub(:save).and_return(false)
        put :update, :id => newslettertimingprogramming.id.to_s, :newslettertimingprogramming => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested newslettertimingprogramming" do
      newslettertimingprogramming = Newslettertimingprogramming.create! valid_attributes
      expect {
        delete :destroy, :id => newslettertimingprogramming.id.to_s
      }.to change(Newslettertimingprogramming, :count).by(-1)
    end

    it "redirects to the newslettertimingprogrammings list" do
      newslettertimingprogramming = Newslettertimingprogramming.create! valid_attributes
      delete :destroy, :id => newslettertimingprogramming.id.to_s
      response.should redirect_to(newslettertimingprogrammings_url)
    end
  end

end
